In [1]:
import numpy as np

#### Random Arrays

In [2]:
np.random.rand(5)

array([0.35801347, 0.14068278, 0.35299346, 0.72401385, 0.8734552 ])

In [4]:
randarr = np.random.rand(5)

In [5]:
#Random Matrix - 2d Array
randmatrix = np.random.rand(5,4)
randmatrix

array([[0.73155073, 0.1176166 , 0.36826586, 0.25493001],
       [0.30343583, 0.04997188, 0.48900356, 0.0906527 ],
       [0.82390232, 0.07809418, 0.90930364, 0.72819051],
       [0.90990707, 0.36289878, 0.17571017, 0.83178847],
       [0.04512251, 0.01798877, 0.00365901, 0.39905452]])

In [6]:
np.floor?

In [9]:
randarray1 = np.random.rand(10)
randarray1

array([0.13417217, 0.70016306, 0.03196327, 0.02168945, 0.76319453,
       0.11421178, 0.7578632 , 0.15778314, 0.62057734, 0.54102177])

In [10]:
randarray1 = randarray1*10
randarray1

array([1.34172173, 7.0016306 , 0.31963274, 0.21689449, 7.63194531,
       1.14211778, 7.57863198, 1.57783139, 6.20577343, 5.41021773])

In [11]:
randarray1 = np.floor(randarray1)
randarray1

array([1., 7., 0., 0., 7., 1., 7., 1., 6., 5.])

In [14]:
#Further simpplified method to generate random integers is np.random.randint
np.random.randint(0,100,10)

array([46, 75, 94, 85, 64, 73, 97, 80, 88, 85])

In [13]:
#random matrix of integers
np.random.randint(0,20,(5,4))

array([[12, 14, 11, 19],
       [11,  5, 17, 19],
       [ 1,  9,  0,  0],
       [17, 17, 17,  8],
       [ 4, 16, 13, 15]])

#### 1. How to extract all numbers between a given range

In [16]:
a = np.random.randint(0,50,100)
a

array([ 6, 23, 21, 47, 17, 21, 40, 26, 43, 14, 33, 24, 43, 40, 22, 10, 29,
       11, 24, 14, 10,  4, 26,  9,  3, 30, 29, 10,  9,  5, 38, 23, 37, 19,
       46, 23, 32, 49, 42, 21, 11, 30, 27,  4,  8, 17, 46, 10, 30, 29, 27,
       28, 36,  0, 48,  9, 49, 10, 32, 45, 46, 42,  7,  7, 44, 24,  5, 29,
       33,  3, 37, 47, 48, 49, 44, 16, 25, 46, 26, 28, 36,  2,  8, 20, 21,
        2, 44, 26, 38,  9, 23, 13, 43, 40,  9, 35,  3, 26, 38, 16])

In [17]:
#>10 & <25
index = np.where((a>=10) & (a<=25))

In [18]:
index

(array([ 1,  2,  4,  5,  9, 11, 14, 15, 17, 18, 19, 20, 27, 31, 33, 35, 39,
        40, 45, 47, 57, 65, 75, 76, 83, 84, 90, 91, 99], dtype=int64),)

In [19]:
outputarray = a[index]
outputarray

array([23, 21, 17, 21, 14, 24, 22, 10, 11, 24, 14, 10, 10, 23, 19, 23, 21,
       11, 17, 10, 10, 24, 16, 25, 20, 21, 23, 13, 16])

#### 2. How to print only 3 decimal places of a python numpy array

In [22]:
randmatrix = np.random.rand(5,4)
randmatrix

array([[0.28752234, 0.23488184, 0.7419324 , 0.92854223],
       [0.68655388, 0.09065203, 0.93161129, 0.83076918],
       [0.47704452, 0.63682851, 0.73157178, 0.09262065],
       [0.91049452, 0.91678743, 0.6701293 , 0.35752609],
       [0.21515716, 0.38492862, 0.00822657, 0.08438092]])

In [23]:
#limit to 3 decimal palces
np.set_printoptions(precision = 3)
randmatrix

array([[0.288, 0.235, 0.742, 0.929],
       [0.687, 0.091, 0.932, 0.831],
       [0.477, 0.637, 0.732, 0.093],
       [0.91 , 0.917, 0.67 , 0.358],
       [0.215, 0.385, 0.008, 0.084]])

#### 3. How to replace a value over a praticular threshold to a constant

In [24]:
# input = [2,3,10,11,12,5,6,7,4,5]
# output = [5,5,10,11,12,5,6,7,5,5]

In [25]:
arr1 = np.random.randint(0,50,20)
arr1

array([37,  1, 14, 30, 39, 10, 38, 39, 16, 38, 38, 31, 11,  7, 17, 10, 48,
       19,  1, 47])

In [29]:
#Lower Threshold = 10
# Upper Threshold = 40
arr1 = np.clip(arr1, a_min=10, a_max=40)
arr1

array([37, 10, 14, 30, 39, 10, 38, 39, 16, 38, 38, 31, 11, 10, 17, 10, 40,
       19, 10, 40])

#### 4. How to get the position of top n values from a numpy array

In [31]:
import numpy as np
samplearray = np.random.randint(0,20,8)
samplearray

array([18,  2,  8,  4,  6,  5, 19,  8])

In [32]:
samplearray.argsort() # arguement -- index -- position

array([1, 3, 5, 4, 2, 7, 0, 6], dtype=int64)

In [34]:
samplearray.argsort()[-3:]

array([7, 0, 6], dtype=int64)

#### 5. How to drop all the missing/null values from the array

In [36]:
a = np.array([1,4,1,5,7,np.nan,9,np.nan])
a

array([ 1.,  4.,  1.,  5.,  7., nan,  9., nan])

In [39]:
np.isnan(a)

array([False, False, False, False, False,  True, False,  True])

In [41]:
a[~np.isnan(a)]

array([1., 4., 1., 5., 7., 9.])

In [42]:
import pandas as pd

In [43]:
samplearray = np.random.randint(0,20,8)
samplearray

array([16, 19,  6,  5,  3,  7, 13,  2])

In [50]:
Series = pd.Series(samplearray[:5] , index = ['a','b','c','d','e'])

In [51]:
Series

a    16
b    19
c     6
d     5
e     3
dtype: int32

In [52]:
Series.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [53]:
Series.values

array([16, 19,  6,  5,  3])

In [54]:
S2 = pd.Series([65,70,89,70] , index = ['Physics','Chemistry','Maths','Comp. Sci'])
S2

Physics      65
Chemistry    70
Maths        89
Comp. Sci    70
dtype: int64

In [55]:
S2[0]

65

In [56]:
S2['Physics']

65

In [59]:
#Series to Tabular Data
S1 = pd.Series(np.random.randint(10000,40000,100))
S1

0     12610
1     34102
2     11964
3     38733
4     18733
      ...  
95    18723
96    22112
97    28765
98    11935
99    25001
Length: 100, dtype: int32

In [60]:
S2 = pd.Series(np.random.randint(220,1200,100))
S2

0     1146
1     1194
2      641
3      590
4     1182
      ... 
95     924
96    1169
97    1103
98     801
99     601
Length: 100, dtype: int32

In [61]:
S3 = pd.Series(np.random.randint(1,5,100))
S3

0     3
1     3
2     1
3     4
4     2
     ..
95    2
96    3
97    1
98    4
99    3
Length: 100, dtype: int32

In [68]:
#Concatenate all the series together
housemkt = pd.concat([S1,S2,S3],axis = 1)
housemkt

0     1  2
0   12610  1146  3
1   34102  1194  3
2   11964   641  1
3   38733   590  4
4   18733  1182  2
..    ...   ... ..
95  18723   924  2
96  22112  1169  3
97  28765  1103  1
98  11935   801  4
99  25001   601  3

[100 rows x 3 columns]

In [67]:
type(housemkt)

pandas.core.frame.DataFrame

In [69]:
housemkt.columns = ['Rent Price','Area in sq ft','No. of rooms']

In [70]:
housemkt

Rent Price  Area in sq ft  No. of rooms
0        12610           1146             3
1        34102           1194             3
2        11964            641             1
3        38733            590             4
4        18733           1182             2
..         ...            ...           ...
95       18723            924             2
96       22112           1169             3
97       28765           1103             1
98       11935            801             4
99       25001            601             3

[100 rows x 3 columns]

In [72]:
import pandas as pd

In [74]:
# Load the data file
df = pd.read_csv(r'C:\Users\skesh\Desktop\Data\Earthquakes.csv.csv')
df

Date      Time  Latitude  Longitude        Type   Depth  \
0      01/02/1965  13:44:18   19.2460   145.6160  Earthquake  131.60   
1      01/04/1965  11:29:49    1.8630   127.3520  Earthquake   80.00   
2      01/05/1965  18:05:58  -20.5790  -173.9720  Earthquake   20.00   
3      01/08/1965  18:49:43  -59.0760   -23.5570  Earthquake   15.00   
4      01/09/1965  13:32:50   11.9380   126.4270  Earthquake   15.00   
...           ...       ...       ...        ...         ...     ...   
23407  12/28/2016  08:22:12   38.3917  -118.8941  Earthquake   12.30   
23408  12/28/2016  09:13:47   38.3777  -118.8957  Earthquake    8.80   
23409  12/28/2016  12:38:51   36.9179   140.4262  Earthquake   10.00   
23410  12/29/2016  22:30:19   -9.0283   118.6639  Earthquake   79.00   
23411  12/30/2016  20:08:28   37.3973   141.4103  Earthquake   11.94   

       Depth Error  Depth Seismic Stations  Magnitude Magnitude Type  ...  \
0              NaN                     NaN        6.0             MW  ...   
1              NaN                     NaN        5.8             MW  ...   
2              NaN                     NaN        6.2             MW  ...   
3              NaN                     NaN        5.8             MW  ...   
4              NaN                     NaN        5.8             MW  ...   
...            ...                     ...        ...            ...  ...   
23407          1.2                    40.0        5.6             ML  ...   
23408          2.0                    33.0        5.5             ML  ...   
23409          1.8                     NaN        5.9            MWW  ...   
23410          1.8                     NaN        6.3            MWW  ...   
23411          2.2                     NaN        5.5             MB  ...   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                             NaN            NaN                  NaN   
1                             NaN            NaN                  NaN   
2                             NaN            NaN                  NaN   
3                             NaN            NaN                  NaN   
4                             NaN            NaN                  NaN   
...                           ...            ...                  ...   
23407                        18.0          42.47                0.120   
23408                        18.0          48.58                0.129   
23409                         NaN          91.00                0.992   
23410                         NaN          26.00                3.553   
23411                       428.0          97.00                0.681   

       Horizontal Error  Root Mean Square            ID  Source  \
0                   NaN               NaN  ISCGEM860706  ISCGEM   
1                   NaN               NaN  ISCGEM860737  ISCGEM   
2                   NaN               NaN  ISCGEM860762  ISCGEM   
3                   NaN               NaN  ISCGEM860856  ISCGEM   
4                   NaN               NaN  ISCGEM860890  ISCGEM   
...                 ...               ...           ...     ...   
23407               NaN            0.1898    NN00570710      NN   
23408               NaN            0.2187    NN00570744      NN   
23409               4.8            1.5200    US10007NAF      US   
23410               6.0            1.4300    US10007NL0      US   
23411               4.5            0.9100    US10007NTD      US   

      Location Source Magnitude Source     Status  
0              ISCGEM           ISCGEM  Automatic  
1              ISCGEM           ISCGEM  Automatic  
2              ISCGEM           ISCGEM  Automatic  
3              ISCGEM           ISCGEM  Automatic  
4              ISCGEM           ISCGEM  Automatic  
...               ...              ...        ...  
23407              NN               NN   Reviewed  
23408              NN               NN   Reviewed  
23409              US               US   Reviewed  
23410              US

In [75]:
type(df)

pandas.core.frame.DataFrame

In [77]:
#Checking the initial few rows in the DataFrames
df.head(10)

Date      Time  Latitude  Longitude        Type  Depth  Depth Error  \
0  01/02/1965  13:44:18    19.246    145.616  Earthquake  131.6          NaN   
1  01/04/1965  11:29:49     1.863    127.352  Earthquake   80.0          NaN   
2  01/05/1965  18:05:58   -20.579   -173.972  Earthquake   20.0          NaN   
3  01/08/1965  18:49:43   -59.076    -23.557  Earthquake   15.0          NaN   
4  01/09/1965  13:32:50    11.938    126.427  Earthquake   15.0          NaN   
5  01/10/1965  13:36:32   -13.405    166.629  Earthquake   35.0          NaN   
6  01/12/1965  13:32:25    27.357     87.867  Earthquake   20.0          NaN   
7  01/15/1965  23:17:42   -13.309    166.212  Earthquake   35.0          NaN   
8  01/16/1965  11:32:37   -56.452    -27.043  Earthquake   95.0          NaN   
9  01/17/1965  10:43:17   -24.563    178.487  Earthquake  565.0          NaN   

   Depth Seismic Stations  Magnitude Magnitude Type  ...  \
0                     NaN        6.0             MW  ...   
1                     NaN        5.8             MW  ...   
2                     NaN        6.2             MW  ...   
3                     NaN        5.8             MW  ...   
4                     NaN        5.8             MW  ...   
5                     NaN        6.7             MW  ...   
6                     NaN        5.9             MW  ...   
7                     NaN        6.0             MW  ...   
8                     NaN        6.0             MW  ...   
9                     NaN        5.8             MW  ...   

   Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                         NaN            NaN                  NaN   
1                         NaN            NaN                  NaN   
2                         NaN            NaN                  NaN   
3                         NaN            NaN                  NaN   
4                         NaN            NaN                  NaN   
5                         NaN            NaN                  NaN   
6                         NaN            NaN                  NaN   
7                         NaN            NaN                  NaN   
8                         NaN            NaN                  NaN   
9                         NaN            NaN                  NaN   

   Horizontal Error  Root Mean Square               ID     Source  \
0               NaN               NaN     ISCGEM860706     ISCGEM   
1               NaN               NaN     ISCGEM860737     ISCGEM   
2               NaN               NaN     ISCGEM860762     ISCGEM   
3               NaN               NaN     ISCGEM860856     ISCGEM   
4               NaN               NaN     ISCGEM860890     ISCGEM   
5               NaN               NaN     ISCGEM860922     ISCGEM   
6               NaN               NaN     ISCGEM861007     ISCGEM   
7               NaN               NaN     ISCGEM861111     ISCGEM   
8               NaN               NaN  ISCGEMSUP861125  ISCGEMSUP   
9               NaN               NaN     ISCGEM861148     ISCGEM   

  Location Source Magnitude Source     Status  
0          ISCGEM           ISCGEM  Automatic  
1          ISCGEM           ISCGEM  Automatic  
2          ISCGEM           ISCGEM  Automatic  
3          ISCGEM           ISCGEM  Automatic  
4          ISCGEM           ISCGEM  Automatic  
5          ISCGEM           ISCGEM  Automatic  
6          ISCGEM           ISCGEM  Automatic  
7          ISCGEM           ISCGEM  Automatic  
8          ISCGEM           ISCGEM  Automatic  
9          ISCGEM           ISCGEM  Automatic  

[10 rows x 21 columns]

In [78]:
#Checking the dimension of the data frame
df.shape

(23412, 21)

In [79]:
#Selecting just one columns
#method 1
df['Date'] # recommend

0        01/02/1965
1        01/04/1965
2        01/05/1965
3        01/08/1965
4        01/09/1965
            ...    
23407    12/28/2016
23408    12/28/2016
23409    12/28/2016
23410    12/29/2016
23411    12/30/2016
Name: Date, Length: 23412, dtype: object

In [80]:
#method 2
df.Date

0        01/02/1965
1        01/04/1965
2        01/05/1965
3        01/08/1965
4        01/09/1965
            ...    
23407    12/28/2016
23408    12/28/2016
23409    12/28/2016
23410    12/29/2016
23411    12/30/2016
Name: Date, Length: 23412, dtype: object

In [82]:
df['Depth Error']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ... 
23407    1.2
23408    2.0
23409    1.8
23410    1.8
23411    2.2
Name: Depth Error, Length: 23412, dtype: float64

In [83]:
df.Depth Error

SyntaxError: invalid syntax (<ipython-input-83-f3d7db85077a>, line 1)

In [85]:
#Selecting multiple columns
df[['Date','Time','Latitude','Longitude']].head(5)

Date      Time  Latitude  Longitude
0  01/02/1965  13:44:18    19.246    145.616
1  01/04/1965  11:29:49     1.863    127.352
2  01/05/1965  18:05:58   -20.579   -173.972
3  01/08/1965  18:49:43   -59.076    -23.557
4  01/09/1965  13:32:50    11.938    126.427

In [86]:
#Check data types
df.dtypes

Date                           object
Time                           object
Latitude                      float64
Longitude                     float64
Type                           object
Depth                         float64
Depth Error                   float64
Depth Seismic Stations        float64
Magnitude                     float64
Magnitude Type                 object
Magnitude Error               float64
Magnitude Seismic Stations    float64
Azimuthal Gap                 float64
Horizontal Distance           float64
Horizontal Error              float64
Root Mean Square              float64
ID                             object
Source                         object
Location Source                object
Magnitude Source               object
Status                         object
dtype: object

In [88]:
df.head(2)

Date      Time  Latitude  Longitude        Type  Depth  Depth Error  \
0  01/02/1965  13:44:18    19.246    145.616  Earthquake  131.6          NaN   
1  01/04/1965  11:29:49     1.863    127.352  Earthquake   80.0          NaN   

   Depth Seismic Stations  Magnitude Magnitude Type  ...  \
0                     NaN        6.0             MW  ...   
1                     NaN        5.8             MW  ...   

   Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                         NaN            NaN                  NaN   
1                         NaN            NaN                  NaN   

   Horizontal Error  Root Mean Square            ID  Source Location Source  \
0               NaN               NaN  ISCGEM860706  ISCGEM          ISCGEM   
1               NaN               NaN  ISCGEM860737  ISCGEM          ISCGEM   

  Magnitude Source     Status  
0           ISCGEM  Automatic  
1           ISCGEM  Automatic  

[2 rows x 21 columns]

In [87]:
#Check the null values
df.isnull()

Date   Time  Latitude  Longitude   Type  Depth  Depth Error  \
0      False  False     False      False  False  False         True   
1      False  False     False      False  False  False         True   
2      False  False     False      False  False  False         True   
3      False  False     False      False  False  False         True   
4      False  False     False      False  False  False         True   
...      ...    ...       ...        ...    ...    ...          ...   
23407  False  False     False      False  False  False        False   
23408  False  False     False      False  False  False        False   
23409  False  False     False      False  False  False        False   
23410  False  False     False      False  False  False        False   
23411  False  False     False      False  False  False        False   

       Depth Seismic Stations  Magnitude  Magnitude Type  ...  \
0                        True      False           False  ...   
1                        True      False           False  ...   
2                        True      False           False  ...   
3                        True      False           False  ...   
4                        True      False           False  ...   
...                       ...        ...             ...  ...   
23407                   False      False           False  ...   
23408                   False      False           False  ...   
23409                    True      False           False  ...   
23410                    True      False           False  ...   
23411                    True      False           False  ...   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                            True           True                 True   
1                            True           True                 True   
2                            True           True                 True   
3                            True           True                 True   
4                            True           True                 True   
...                           ...            ...                  ...   
23407                       False          False                False   
23408                       False          False                False   
23409                        True          False                False   
23410                        True          False                False   
23411                       False          False                False   

       Horizontal Error  Root Mean Square     ID  Source  Location Source  \
0                  True              True  False   False            False   
1                  True              True  False   False            False   
2                  True              True  False   False            False   
3                  True              True  False   False            False   
4                  True              True  False   False            False   
...                 ...               ...    ...     ...              ...   
23407              True             False  False   False            False   
23408              True             False  False   False            False   
23409             False             False  False   False            False   
23410             False             False  False   False            False   
23411             False             False  False   False            False   

       Magnitude Source  Status  
0                 False   False  
1                 False   False  
2                 False   False  
3                 False   False  
4                 False   False  
...                 ...     ...  
23407             False   False  
23408             False   False  
23409             False   False  
23410             False   False  
23411             False   False  

[23412 rows x 21 columns]

In [89]:
df.isnull().sum()

Date                              0
Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                   18951
Depth Seismic Stations        16315
Magnitude                         0
Magnitude Type                    3
Magnitude Error               23085
Magnitude Seismic Stations    20848
Azimuthal Gap                 16113
Horizontal Distance           21808
Horizontal Error              22256
Root Mean Square               6060
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

In [90]:
df['Magnitude'].max()

9.1

In [91]:
df['Magnitude'].min()

5.5

In [92]:
df['Magnitude'].mean()

5.882530753460003

In [93]:
df['Magnitude'].sum()

137721.81

In [95]:
df['Magnitude Type'].mode()

0    MW
dtype: object

In [96]:
df['Magnitude Type'].mode()[0]

'MW'

In [99]:
#how fill in the missing values
print('Total Number of null in the column ',df['Magnitude Type'].isnull().sum())

df['Magnitude Type'].fillna(df['Magnitude Type'].mode()[0] ,inplace = True)

Total Number of null in the column  3


In [100]:
print('Total Number of null in the column ',df['Magnitude Type'].isnull().sum())

Total Number of null in the column  0


In [104]:
#How to delete a column
df.drop(columns = 'Depth Seismic Stations',inplace = True)
#df = df.drop(columns = 'Depth Seismic Stations')

In [105]:
df

Date      Time  Latitude  Longitude        Type   Depth  \
0      01/02/1965  13:44:18   19.2460   145.6160  Earthquake  131.60   
1      01/04/1965  11:29:49    1.8630   127.3520  Earthquake   80.00   
2      01/05/1965  18:05:58  -20.5790  -173.9720  Earthquake   20.00   
3      01/08/1965  18:49:43  -59.0760   -23.5570  Earthquake   15.00   
4      01/09/1965  13:32:50   11.9380   126.4270  Earthquake   15.00   
...           ...       ...       ...        ...         ...     ...   
23407  12/28/2016  08:22:12   38.3917  -118.8941  Earthquake   12.30   
23408  12/28/2016  09:13:47   38.3777  -118.8957  Earthquake    8.80   
23409  12/28/2016  12:38:51   36.9179   140.4262  Earthquake   10.00   
23410  12/29/2016  22:30:19   -9.0283   118.6639  Earthquake   79.00   
23411  12/30/2016  20:08:28   37.3973   141.4103  Earthquake   11.94   

       Depth Error  Magnitude Magnitude Type  Magnitude Error  \
0              NaN        6.0             MW              NaN   
1              NaN        5.8             MW              NaN   
2              NaN        6.2             MW              NaN   
3              NaN        5.8             MW              NaN   
4              NaN        5.8             MW              NaN   
...            ...        ...            ...              ...   
23407          1.2        5.6             ML            0.320   
23408          2.0        5.5             ML            0.260   
23409          1.8        5.9            MWW              NaN   
23410          1.8        6.3            MWW              NaN   
23411          2.2        5.5             MB            0.029   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                             NaN            NaN                  NaN   
1                             NaN            NaN                  NaN   
2                             NaN            NaN                  NaN   
3                             NaN            NaN                  NaN   
4                             NaN            NaN                  NaN   
...                           ...            ...                  ...   
23407                        18.0          42.47                0.120   
23408                        18.0          48.58                0.129   
23409                         NaN          91.00                0.992   
23410                         NaN          26.00                3.553   
23411                       428.0          97.00                0.681   

       Horizontal Error  Root Mean Square            ID  Source  \
0                   NaN               NaN  ISCGEM860706  ISCGEM   
1                   NaN               NaN  ISCGEM860737  ISCGEM   
2                   NaN               NaN  ISCGEM860762  ISCGEM   
3                   NaN               NaN  ISCGEM860856  ISCGEM   
4                   NaN               NaN  ISCGEM860890  ISCGEM   
...                 ...               ...           ...     ...   
23407               NaN            0.1898    NN00570710      NN   
23408               NaN            0.2187    NN00570744      NN   
23409               4.8            1.5200    US10007NAF      US   
23410               6.0            1.4300    US10007NL0      US   
23411               4.5            0.9100    US10007NTD      US   

      Location Source Magnitude Source     Status  
0              ISCGEM           ISCGEM  Automatic  
1              ISCGEM           ISCGEM  Automatic  
2              ISCGEM           ISCGEM  Automatic  
3              ISCGEM           ISCGEM  Automatic  
4              ISCGEM           ISCGEM  Automatic  
...               ...              ...        ...  
23407              NN               NN   Reviewed  
23408              NN               NN   Reviewed  
23409              US               US   Reviewed  
23410              US               US   Reviewed  
23411              US               US   Reviewed  

[23412 rows x 20 columns]

In [109]:
#Finding the unique value in a columns
print('Total Number of unique values in the column ',df['Magnitude Type'].unique())

print('Count of unique values in the column ',df['Magnitude Type'].nunique())

Total Number of unique values in the column  ['MW' 'ML' 'MH' 'MS' 'MB' 'MWC' 'MD' 'MWB' 'MWW' 'MWR']
Count of unique values in the column  10


In [111]:
df['Type'].unique()

array(['Earthquake', 'Nuclear Explosion', 'Explosion', 'Rock Burst'],
      dtype=object)

In [113]:
df['Type'].value_counts()

Earthquake           23232
Nuclear Explosion      175
Explosion                4
Rock Burst               1
Name: Type, dtype: int64

In [115]:
df['Magnitude Type'].value_counts()

MW     7725
MWC    5669
MB     3761
MWB    2458
MWW    1983
MS     1702
ML       77
MWR      26
MD        6
MH        5
Name: Magnitude Type, dtype: int64

In [116]:
df['Magnitude Type'].value_counts(normalize=True)

MW     0.329959
MWC    0.242141
MB     0.160644
MWB    0.104989
MWW    0.084700
MS     0.072698
ML     0.003289
MWR    0.001111
MD     0.000256
MH     0.000214
Name: Magnitude Type, dtype: float64

In [118]:
#Sort a dataframe on the basis of a column value
df[['Date','Time','Latitude','Longitude','Magnitude']].head(5)

Date      Time  Latitude  Longitude  Magnitude
0  01/02/1965  13:44:18    19.246    145.616        6.0
1  01/04/1965  11:29:49     1.863    127.352        5.8
2  01/05/1965  18:05:58   -20.579   -173.972        6.2
3  01/08/1965  18:49:43   -59.076    -23.557        5.8
4  01/09/1965  13:32:50    11.938    126.427        5.8

In [119]:
df[['Date','Time','Latitude','Longitude','Magnitude']].sort_values(by='Magnitude')

Date      Time  Latitude  Longitude  Magnitude
23411  12/30/2016  20:08:28   37.3973   141.4103        5.5
4419   08/19/1977  07:38:05  -10.1920   117.4120        5.5
13282  10/31/1996  18:18:43    9.9020   126.3870        5.5
4414   08/16/1977  06:15:17  -19.2800   167.6550        5.5
13293  11/04/1996  22:54:16   43.5230  -127.3560        5.5
...           ...       ...       ...        ...        ...
21219  04/11/2012  08:38:37    2.3270    93.0630        8.6
16     02/04/1965  05:01:22   51.2510   178.7150        8.7
19928  02/27/2010  06:34:12  -36.1220   -72.8980        8.8
20501  03/11/2011  05:46:24   38.2970   142.3730        9.1
17083  12/26/2004  00:58:53    3.2950    95.9820        9.1

[23412 rows x 5 columns]

In [120]:
df[['Date','Time','Latitude','Longitude','Magnitude']].sort_values(by='Magnitude',ascending = False)

Date      Time  Latitude  Longitude  Magnitude
20501  03/11/2011  05:46:24   38.2970   142.3730        9.1
17083  12/26/2004  00:58:53    3.2950    95.9820        9.1
19928  02/27/2010  06:34:12  -36.1220   -72.8980        8.8
16     02/04/1965  05:01:22   51.2510   178.7150        8.7
17329  03/28/2005  16:09:37    2.0850    97.1080        8.6
...           ...       ...       ...        ...        ...
9918   04/06/1990  06:17:43   15.5360   147.4630        5.5
9920   04/06/1990  14:31:46  -21.6180  -174.2130        5.5
18946  04/11/2008  05:02:53   16.1740   144.8850        5.5
18945  04/11/2008  03:16:40   16.0990   144.9580        5.5
23411  12/30/2016  20:08:28   37.3973   141.4103        5.5

[23412 rows x 5 columns]

In [121]:
df.describe()

Latitude     Longitude         Depth  Depth Error     Magnitude  \
count  23412.000000  23412.000000  23412.000000  4461.000000  23412.000000   
mean       1.679033     39.639961     70.767911     4.993115      5.882531   
std       30.113183    125.511959    122.651898     4.875184      0.423066   
min      -77.080000   -179.997000     -1.100000     0.000000      5.500000   
25%      -18.653000    -76.349750     14.522500     1.800000      5.600000   
50%       -3.568500    103.982000     33.000000     3.500000      5.700000   
75%       26.190750    145.026250     54.000000     6.300000      6.000000   
max       86.005000    179.998000    700.000000    91.295000      9.100000   

       Magnitude Error  Magnitude Seismic Stations  Azimuthal Gap  \
count       327.000000                 2564.000000    7299.000000   
mean          0.071820                   48.944618      44.163532   
std           0.051466                   62.943106      32.141486   
min           0.000000                    0.000000       0.000000   
25%           0.046000                   10.000000      24.100000   
50%           0.059000                   28.000000      36.000000   
75%           0.075500                   66.000000      54.000000   
max           0.410000                  821.000000     360.000000   

       Horizontal Distance  Horizontal Error  Root Mean Square  
count          1604.000000       1156.000000      17352.000000  
mean              3.992660          7.662759          1.022784  
std               5.377262         10.430396          0.188545  
min               0.004505          0.085000          0.000000  
25%               0.968750          5.300000          0.900000  
50%               2.319500          6.700000          1.000000  
75%               4.724500          8.100000          1.130000  
max              37.874000         99.000000          3.440000

In [122]:
#Filtering a DataFrame
df[df['Type'] == 'Nuclear Explosion']

Date      Time   Latitude   Longitude               Type  Depth  \
565    12/20/1966  15:30:01  37.302167 -116.408333  Nuclear Explosion    1.2   
897    04/26/1968  15:00:02  37.295333 -116.455667  Nuclear Explosion    1.2   
1129   12/19/1968  16:30:01  37.231500 -116.473667  Nuclear Explosion    1.4   
1380   09/16/1969  14:30:01  37.314167 -116.460667  Nuclear Explosion    1.2   
1532   03/26/1970  19:00:01  37.300500 -116.534167  Nuclear Explosion    1.2   
...           ...       ...        ...         ...                ...    ...   
11963  06/10/1994  06:25:58  41.527000   88.710000  Nuclear Explosion    0.0   
12142  10/07/1994  03:25:58  41.662000   88.753000  Nuclear Explosion    0.0   
12450  05/15/1995  04:05:58  41.603000   88.820000  Nuclear Explosion    0.0   
12613  08/17/1995  00:59:58  41.559000   88.800000  Nuclear Explosion    0.0   
13054  06/08/1996  02:55:58  41.657000   88.690000  Nuclear Explosion    0.0   

       Depth Error  Magnitude Magnitude Type  Magnitude Error  \
565          31.61       5.62             ML            0.245   
897          31.61       5.63             ML            0.125   
1129         31.61       5.52             ML            0.219   
1380         31.61       5.82             ML            0.187   
1532         31.61       5.54             ML            0.410   
...            ...        ...            ...              ...   
11963          NaN       5.80             MB              NaN   
12142          NaN       6.00             MB              NaN   
12450          NaN       6.10             MB              NaN   
12613          NaN       6.00             MB              NaN   
13054          NaN       5.90             MB              NaN   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
565                          10.0          261.0                1.476   
897                           6.0          261.0                1.438   
1129                          6.0          257.0                1.415   
1380                          8.0          268.0                1.437   
1532                         10.0          260.0                1.377   
...                           ...            ...                  ...   
11963                       133.0            NaN                  NaN   
12142                       138.0            NaN                  NaN   
12450                       175.0            NaN                  NaN   
12613                       166.0            NaN                  NaN   
13054                       178.0            NaN                  NaN   

       Horizontal Error  Root Mean Square          ID Source Location Source  \
565                99.0              0.86   CI3329931     CI              CI   
897                99.0              1.03   CI3342128     CI              CI   
1129               99.0              1.36   CI3342181     CI              CI   
1380               99.0              0.33   CI3326197     CI              CI   
1532               99.0              0.35   CI3325031     CI              CI   
...                 ...               ...         ...    ...             ...   
11963               NaN              0.90  USP0006E1A     US              US   
12142               NaN              0.90  USP0006KQC     US              US   
12450               NaN              1.00  USP0006XCY     US              US   
12613               NaN              0.90  USP00071XV     US              US   
13054               NaN              0.90  USP0007J9V     US              US   

      Magnitude Source    Status  
565                 CI  Reviewed  
897                 CI  Reviewed  
1129                CI  Reviewed  
1380                CI  Reviewed  
1532                CI  Reviewed  
...                ...       ...  
11963               US  Reviewed  
12142               US  Reviewed  
12450               US  Reviewed  
12613               US  Reviewed  
13054               US  Reviewed  

[175 rows x 

In [123]:
#applying multiple filters
df[(df['Type'] == 'Nuclear Explosion') | (df['Type'] == 'Explosion')]

Date      Time   Latitude   Longitude               Type  Depth  \
565    12/20/1966  15:30:01  37.302167 -116.408333  Nuclear Explosion    1.2   
897    04/26/1968  15:00:02  37.295333 -116.455667  Nuclear Explosion    1.2   
1129   12/19/1968  16:30:01  37.231500 -116.473667  Nuclear Explosion    1.4   
1380   09/16/1969  14:30:01  37.314167 -116.460667  Nuclear Explosion    1.2   
1532   03/26/1970  19:00:01  37.300500 -116.534167  Nuclear Explosion    1.2   
...           ...       ...        ...         ...                ...    ...   
11963  06/10/1994  06:25:58  41.527000   88.710000  Nuclear Explosion    0.0   
12142  10/07/1994  03:25:58  41.662000   88.753000  Nuclear Explosion    0.0   
12450  05/15/1995  04:05:58  41.603000   88.820000  Nuclear Explosion    0.0   
12613  08/17/1995  00:59:58  41.559000   88.800000  Nuclear Explosion    0.0   
13054  06/08/1996  02:55:58  41.657000   88.690000  Nuclear Explosion    0.0   

       Depth Error  Magnitude Magnitude Type  Magnitude Error  \
565          31.61       5.62             ML            0.245   
897          31.61       5.63             ML            0.125   
1129         31.61       5.52             ML            0.219   
1380         31.61       5.82             ML            0.187   
1532         31.61       5.54             ML            0.410   
...            ...        ...            ...              ...   
11963          NaN       5.80             MB              NaN   
12142          NaN       6.00             MB              NaN   
12450          NaN       6.10             MB              NaN   
12613          NaN       6.00             MB              NaN   
13054          NaN       5.90             MB              NaN   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
565                          10.0          261.0                1.476   
897                           6.0          261.0                1.438   
1129                          6.0          257.0                1.415   
1380                          8.0          268.0                1.437   
1532                         10.0          260.0                1.377   
...                           ...            ...                  ...   
11963                       133.0            NaN                  NaN   
12142                       138.0            NaN                  NaN   
12450                       175.0            NaN                  NaN   
12613                       166.0            NaN                  NaN   
13054                       178.0            NaN                  NaN   

       Horizontal Error  Root Mean Square          ID Source Location Source  \
565                99.0              0.86   CI3329931     CI              CI   
897                99.0              1.03   CI3342128     CI              CI   
1129               99.0              1.36   CI3342181     CI              CI   
1380               99.0              0.33   CI3326197     CI              CI   
1532               99.0              0.35   CI3325031     CI              CI   
...                 ...               ...         ...    ...             ...   
11963               NaN              0.90  USP0006E1A     US              US   
12142               NaN              0.90  USP0006KQC     US              US   
12450               NaN              1.00  USP0006XCY     US              US   
12613               NaN              0.90  USP00071XV     US              US   
13054               NaN              0.90  USP0007J9V     US              US   

      Magnitude Source    Status  
565                 CI  Reviewed  
897                 CI  Reviewed  
1129                CI  Reviewed  
1380                CI  Reviewed  
1532                CI  Reviewed  
...                ...       ...  
11963               US  Reviewed  
12142               US  Reviewed  
12450               US  Reviewed  
12613               US  Reviewed  
13054               US  Reviewed  

[179 rows x 

In [126]:
df[(df['Type'] == 'Nuclear Explosion') | (df['Type'] == 'Explosion') | (df['Magnitude'] > 6)]

Date      Time  Latitude  Longitude        Type   Depth  \
2      01/05/1965  18:05:58  -20.5790  -173.9720  Earthquake   20.00   
5      01/10/1965  13:36:32  -13.4050   166.6290  Earthquake   35.00   
11     01/24/1965  00:11:17   -2.6080   125.9520  Earthquake   20.00   
15     02/04/1965  03:25:00  -51.8400   139.7410  Earthquake   10.00   
16     02/04/1965  05:01:22   51.2510   178.7150  Earthquake   30.30   
...           ...       ...       ...        ...         ...     ...   
23394  12/18/2016  13:30:11   -9.9640   -70.9714  Earthquake  622.54   
23395  12/20/2016  04:21:29  -10.1773   161.2236  Earthquake   16.65   
23399  12/21/2016  00:17:15   -7.5082   127.9206  Earthquake  152.00   
23403  12/25/2016  14:22:27  -43.4029   -73.9395  Earthquake   38.00   
23410  12/29/2016  22:30:19   -9.0283   118.6639  Earthquake   79.00   

       Depth Error  Magnitude Magnitude Type  Magnitude Error  \
2              NaN        6.2             MW              NaN   
5              NaN        6.7             MW              NaN   
11             NaN        8.2             MW              NaN   
15             NaN        6.1             MW              NaN   
16             NaN        8.7             MW              NaN   
...            ...        ...            ...              ...   
23394          3.1        6.4            MWW              NaN   
23395          2.8        6.4            MWW              NaN   
23399          1.8        6.7            MWW              NaN   
23403          1.9        7.6            MWW              NaN   
23410          1.8        6.3            MWW              NaN   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
2                             NaN            NaN                  NaN   
5                             NaN            NaN                  NaN   
11                            NaN            NaN                  NaN   
15                            NaN            NaN                  NaN   
16                            NaN            NaN                  NaN   
...                           ...            ...                  ...   
23394                         NaN           11.0                2.804   
23395                         NaN           21.0                1.456   
23399                         NaN           17.0                3.380   
23403                         NaN           29.0                0.351   
23410                         NaN           26.0                3.553   

       Horizontal Error  Root Mean Square                         ID  \
2                   NaN               NaN               ISCGEM860762   
5                   NaN               NaN               ISCGEM860922   
11                  NaN               NaN               ISCGEM861299   
15                  NaN               NaN               ISCGEM859200   
16                  NaN               NaN  OFFICIAL19650204050122_30   
...                 ...               ...                        ...   
23394               9.1              0.65                 US200082AN   
23395               8.1              0.89                 US200082PP   
23399               5.3              1.20                 US10007LKW   
23403               6.8              0.80                 US10007MN3   
23410               6.0              1.43                 US10007NL0   

         Source Location Source Magnitude Source     Status  
2        ISCGEM          ISCGEM           ISCGEM  Automatic  
5        ISCGEM          ISCGEM           ISCGEM  Automatic  
11       ISCGEM          ISCGEM           ISCGEM  Automatic  
15       ISCGEM          ISCGEM           ISCGEM  Automatic  
16     OFFICIAL          ISCGEM         OFFICIAL  Automatic  
...         ...             ...              ...        ...  
23394        US              US               US   Reviewed  
23395        US              US               US   Reviewed  
23399        US              US               US   Reviewed  
23403

In [128]:
df[(df['Type'] == 'Nuclear Explosion') | (df['Type'] == 'Explosion')][df['Magnitude'] > 6]

C:\Users\skesh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


Date      Time  Latitude  Longitude               Type  Depth  \
2797   07/23/1973  01:22:58    49.986     78.853  Nuclear Explosion    0.0   
2859   09/12/1973  06:59:54    73.302     55.161  Nuclear Explosion    0.0   
2897   10/27/1973  06:59:57    70.779     54.177  Nuclear Explosion    0.0   
3218   08/29/1974  09:59:55    73.366     55.094  Nuclear Explosion    0.0   
3286   11/02/1974  04:59:57    70.817     54.063  Nuclear Explosion    0.0   
3593   08/23/1975  08:59:58    73.369     54.641          Explosion    0.0   
3661   10/18/1975  08:59:56    70.843     53.690  Nuclear Explosion    0.0   
3663   10/21/1975  11:59:57    73.351     55.078  Nuclear Explosion    0.0   
5198   06/23/1979  02:56:58    49.918     78.915  Nuclear Explosion    0.0   
5234   08/04/1979  03:56:57    49.901     78.959  Nuclear Explosion    0.0   
5248   08/18/1979  02:51:57    49.971     79.010  Nuclear Explosion    0.0   
5388   12/23/1979  04:56:58    49.964     78.827  Nuclear Explosion    0.0   
5635   09/14/1980  02:42:39    49.976     78.889  Nuclear Explosion    0.0   
6061   12/27/1981  03:43:14    49.909     78.873  Nuclear Explosion    0.0   
6177   04/25/1982  03:23:05    49.889     78.931  Nuclear Explosion    0.0   
6230   07/04/1982  01:17:14    49.995     78.856  Nuclear Explosion    0.0   
6363   12/05/1982  03:37:13    49.928     78.869  Nuclear Explosion    0.0   
6613   06/12/1983  02:36:44    49.906     78.981  Nuclear Explosion    0.0   
6774   10/26/1983  01:55:05    49.921     78.907  Nuclear Explosion    0.0   
7109   07/14/1984  01:09:11    49.891     78.963  Nuclear Explosion    0.0   
7244   10/27/1984  01:50:11    49.949     78.834  Nuclear Explosion    0.0   
7322   12/16/1984  03:55:03    49.957     78.862  Nuclear Explosion    0.0   
8457   04/03/1987  01:17:08    49.928     78.829  Nuclear Explosion    0.0   
8531   06/05/1987  04:59:58    41.584     88.737  Nuclear Explosion    0.0   
8561   06/20/1987  00:53:05    49.913     78.735  Nuclear Explosion    0.0   
8795   12/13/1987  03:21:05    49.989     78.844  Nuclear Explosion    0.0   
8808   12/27/1987  03:05:05    49.864     78.758  Nuclear Explosion    0.0   
8877   02/13/1988  03:05:06    49.954     78.910  Nuclear Explosion    0.0   
8952   04/03/1988  01:33:06    49.917     78.945  Nuclear Explosion    0.0   
8989   05/04/1988  00:57:07    49.928     78.769  Nuclear Explosion    0.0   
9166   09/14/1988  03:59:57    49.833     78.808  Nuclear Explosion    0.0   
9327   01/22/1989  03:57:07    49.924     78.831  Nuclear Explosion    0.0   
10126  08/16/1990  04:59:58    41.564     88.770  Nuclear Explosion    0.0   
10907  05/21/1992  04:59:58    41.604     88.813  Nuclear Explosion    0.0   
12450  05/15/1995  04:05:58    41.603     88.820  Nuclear Explosion    0.0   

       Depth Error  Magnitude Magnitude Type  Magnitude Error  \
2797           NaN        6.3             MB              NaN   
2859           NaN        6.8             MB              NaN   
2897           NaN        6.9             MB              NaN   
3218           NaN        6.4             MB              NaN   
3286           NaN        6.7             MB              NaN   
3593           NaN        6.4             MB              NaN   
3661           NaN        6.7             MB              NaN   
3663           NaN        6.5             MB              NaN   
5198           NaN        6.3             MB              NaN   
5234           NaN        6.1             MB              NaN   
5248           NaN        6.1             MB              NaN   
5388           NaN        6.1             MB              NaN   
5635           NaN        6.2             MB              NaN   
6061           NaN        6.2             MB              NaN   
6177           NaN        6.1             MB              NaN   
6230           NaN        6.1             MB              NaN   
6363           NaN        6.1             MB              NaN   
6613           NaN        6.1     

In [140]:
df[(df['Type'] == 'Nuclear Explosion') | (df['Type'] == 'Explosion')][df['Magnitude']> 6]

Date      Time   Latitude   Longitude               Type  Depth  \
565    12/20/1966  15:30:01  37.302167 -116.408333  Nuclear Explosion    1.2   
897    04/26/1968  15:00:02  37.295333 -116.455667  Nuclear Explosion    1.2   
1129   12/19/1968  16:30:01  37.231500 -116.473667  Nuclear Explosion    1.4   
1380   09/16/1969  14:30:01  37.314167 -116.460667  Nuclear Explosion    1.2   
1532   03/26/1970  19:00:01  37.300500 -116.534167  Nuclear Explosion    1.2   
...           ...       ...        ...         ...                ...    ...   
11963  06/10/1994  06:25:58  41.527000   88.710000  Nuclear Explosion    0.0   
12142  10/07/1994  03:25:58  41.662000   88.753000  Nuclear Explosion    0.0   
12450  05/15/1995  04:05:58  41.603000   88.820000  Nuclear Explosion    0.0   
12613  08/17/1995  00:59:58  41.559000   88.800000  Nuclear Explosion    0.0   
13054  06/08/1996  02:55:58  41.657000   88.690000  Nuclear Explosion    0.0   

       Depth Error  Magnitude Magnitude Type  Magnitude Error  \
565          31.61       5.62             ML            0.245   
897          31.61       5.63             ML            0.125   
1129         31.61       5.52             ML            0.219   
1380         31.61       5.82             ML            0.187   
1532         31.61       5.54             ML            0.410   
...            ...        ...            ...              ...   
11963          NaN       5.80             MB              NaN   
12142          NaN       6.00             MB              NaN   
12450          NaN       6.10             MB              NaN   
12613          NaN       6.00             MB              NaN   
13054          NaN       5.90             MB              NaN   

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
565                          10.0          261.0                1.476   
897                           6.0          261.0                1.438   
1129                          6.0          257.0                1.415   
1380                          8.0          268.0                1.437   
1532                         10.0          260.0                1.377   
...                           ...            ...                  ...   
11963                       133.0            NaN                  NaN   
12142                       138.0            NaN                  NaN   
12450                       175.0            NaN                  NaN   
12613                       166.0            NaN                  NaN   
13054                       178.0            NaN                  NaN   

       Horizontal Error  Root Mean Square          ID Source Location Source  \
565                99.0              0.86   CI3329931     CI              CI   
897                99.0              1.03   CI3342128     CI              CI   
1129               99.0              1.36   CI3342181     CI              CI   
1380               99.0              0.33   CI3326197     CI              CI   
1532               99.0              0.35   CI3325031     CI              CI   
...                 ...               ...         ...    ...             ...   
11963               NaN              0.90  USP0006E1A     US              US   
12142               NaN              0.90  USP0006KQC     US              US   
12450               NaN              1.00  USP0006XCY     US              US   
12613               NaN              0.90  USP00071XV     US              US   
13054               NaN              0.90  USP0007J9V     US              US   

      Magnitude Source    Status  
565                 CI  Reviewed  
897                 CI  Reviewed  
1129                CI  Reviewed  
1380                CI  Reviewed  
1532                CI  Reviewed  
...                ...       ...  
11963               US  Reviewed  
12142               US  Reviewed  
12450               US  Reviewed  
12613               US  Reviewed  
13054               US  Reviewed  

[179 rows x 

In [129]:
BirEarthquakes = df[(df['Type'] == 'Nuclear Explosion') | (df['Type'] == 'Explosion')][df['Magnitude'] > 6]

C:\Users\skesh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


In [134]:
BirEarthquakes.head(4)

Date      Time  Latitude  Longitude               Type  Depth  \
2797  07/23/1973  01:22:58    49.986     78.853  Nuclear Explosion    0.0   
2859  09/12/1973  06:59:54    73.302     55.161  Nuclear Explosion    0.0   
2897  10/27/1973  06:59:57    70.779     54.177  Nuclear Explosion    0.0   
3218  08/29/1974  09:59:55    73.366     55.094  Nuclear Explosion    0.0   

      Depth Error  Magnitude Magnitude Type  Magnitude Error  \
2797          NaN        6.3             MB              NaN   
2859          NaN        6.8             MB              NaN   
2897          NaN        6.9             MB              NaN   
3218          NaN        6.4             MB              NaN   

      Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
2797                         NaN            NaN                  NaN   
2859                         NaN            NaN                  NaN   
2897                         NaN            NaN                  NaN   
3218                         NaN            NaN                  NaN   

      Horizontal Error  Root Mean Square          ID Source Location Source  \
2797               NaN               NaN  USP00002TP     US              US   
2859               NaN               NaN  USP00003DP     US              US   
2897               NaN               NaN  USP00003YA     US              US   
3218               NaN               NaN  USP00007UG     US              US   

     Magnitude Source    Status  
2797               US  Reviewed  
2859               US  Reviewed  
2897               US  Reviewed  
3218               US  Reviewed

In [135]:
BirEarthquakes.reset_index().head(4)

index        Date      Time  Latitude  Longitude               Type  Depth  \
0   2797  07/23/1973  01:22:58    49.986     78.853  Nuclear Explosion    0.0   
1   2859  09/12/1973  06:59:54    73.302     55.161  Nuclear Explosion    0.0   
2   2897  10/27/1973  06:59:57    70.779     54.177  Nuclear Explosion    0.0   
3   3218  08/29/1974  09:59:55    73.366     55.094  Nuclear Explosion    0.0   

   Depth Error  Magnitude Magnitude Type  ...  Magnitude Seismic Stations  \
0          NaN        6.3             MB  ...                         NaN   
1          NaN        6.8             MB  ...                         NaN   
2          NaN        6.9             MB  ...                         NaN   
3          NaN        6.4             MB  ...                         NaN   

   Azimuthal Gap  Horizontal Distance  Horizontal Error  Root Mean Square  \
0            NaN                  NaN               NaN               NaN   
1            NaN                  NaN               NaN               NaN   
2            NaN                  NaN               NaN               NaN   
3            NaN                  NaN               NaN               NaN   

           ID Source Location Source Magnitude Source    Status  
0  USP00002TP     US              US               US  Reviewed  
1  USP00003DP     US              US               US  Reviewed  
2  USP00003YA     US              US               US  Reviewed  
3  USP00007UG     US              US               US  Reviewed  

[4 rows x 21 columns]

In [138]:
BirEarthquakes.reset_index(drop=True,inplace = True)

In [139]:
BirEarthquakes

Date      Time  Latitude  Longitude               Type  Depth  \
0   07/23/1973  01:22:58    49.986     78.853  Nuclear Explosion    0.0   
1   09/12/1973  06:59:54    73.302     55.161  Nuclear Explosion    0.0   
2   10/27/1973  06:59:57    70.779     54.177  Nuclear Explosion    0.0   
3   08/29/1974  09:59:55    73.366     55.094  Nuclear Explosion    0.0   
4   11/02/1974  04:59:57    70.817     54.063  Nuclear Explosion    0.0   
5   08/23/1975  08:59:58    73.369     54.641          Explosion    0.0   
6   10/18/1975  08:59:56    70.843     53.690  Nuclear Explosion    0.0   
7   10/21/1975  11:59:57    73.351     55.078  Nuclear Explosion    0.0   
8   06/23/1979  02:56:58    49.918     78.915  Nuclear Explosion    0.0   
9   08/04/1979  03:56:57    49.901     78.959  Nuclear Explosion    0.0   
10  08/18/1979  02:51:57    49.971     79.010  Nuclear Explosion    0.0   
11  12/23/1979  04:56:58    49.964     78.827  Nuclear Explosion    0.0   
12  09/14/1980  02:42:39    49.976     78.889  Nuclear Explosion    0.0   
13  12/27/1981  03:43:14    49.909     78.873  Nuclear Explosion    0.0   
14  04/25/1982  03:23:05    49.889     78.931  Nuclear Explosion    0.0   
15  07/04/1982  01:17:14    49.995     78.856  Nuclear Explosion    0.0   
16  12/05/1982  03:37:13    49.928     78.869  Nuclear Explosion    0.0   
17  06/12/1983  02:36:44    49.906     78.981  Nuclear Explosion    0.0   
18  10/26/1983  01:55:05    49.921     78.907  Nuclear Explosion    0.0   
19  07/14/1984  01:09:11    49.891     78.963  Nuclear Explosion    0.0   
20  10/27/1984  01:50:11    49.949     78.834  Nuclear Explosion    0.0   
21  12/16/1984  03:55:03    49.957     78.862  Nuclear Explosion    0.0   
22  04/03/1987  01:17:08    49.928     78.829  Nuclear Explosion    0.0   
23  06/05/1987  04:59:58    41.584     88.737  Nuclear Explosion    0.0   
24  06/20/1987  00:53:05    49.913     78.735  Nuclear Explosion    0.0   
25  12/13/1987  03:21:05    49.989     78.844  Nuclear Explosion    0.0   
26  12/27/1987  03:05:05    49.864     78.758  Nuclear Explosion    0.0   
27  02/13/1988  03:05:06    49.954     78.910  Nuclear Explosion    0.0   
28  04/03/1988  01:33:06    49.917     78.945  Nuclear Explosion    0.0   
29  05/04/1988  00:57:07    49.928     78.769  Nuclear Explosion    0.0   
30  09/14/1988  03:59:57    49.833     78.808  Nuclear Explosion    0.0   
31  01/22/1989  03:57:07    49.924     78.831  Nuclear Explosion    0.0   
32  08/16/1990  04:59:58    41.564     88.770  Nuclear Explosion    0.0   
33  05/21/1992  04:59:58    41.604     88.813  Nuclear Explosion    0.0   
34  05/15/1995  04:05:58    41.603     88.820  Nuclear Explosion    0.0   

    Depth Error  Magnitude Magnitude Type  Magnitude Error  \
0           NaN        6.3             MB              NaN   
1           NaN        6.8             MB              NaN   
2           NaN        6.9             MB              NaN   
3           NaN        6.4             MB              NaN   
4           NaN        6.7             MB              NaN   
5           NaN        6.4             MB              NaN   
6           NaN        6.7             MB              NaN   
7           NaN        6.5             MB              NaN   
8           NaN        6.3             MB              NaN   
9           NaN        6.1             MB              NaN   
10          NaN        6.1             MB              NaN   
11          NaN        6.1             MB              NaN   
12          NaN        6.2             MB              NaN   
13          NaN        6.2             MB              NaN   
14          NaN        6.1             MB              NaN   
15          NaN        6.1             MB              NaN   
16          NaN        6.1             MB              NaN   
17          NaN        6.1             MB              NaN   
18          NaN        6.1             MB              NaN   
19          NaN        6.2             MB              NaN   
20     