Classes and Objects in Python

Numpy

In [1]:
my_list = [1,2,3,4,5]

In [2]:
type(my_list)

list

In [4]:
class SampleClass:  
    pass

In [5]:
s1 = SampleClass()

In [6]:
type(s1)

__main__.SampleClass

In [13]:
class MobilePhone():
    
    def __init__(self,Price,Model): #acts as constructor
                                    #constructor is something which activates an object
        self.m = Model
        self.p = Price

In [14]:
m1 = MobilePhone()

TypeError: __init__() missing 2 required positional arguments: 'Price' and 'Model'

In [15]:
m1 = MobilePhone(10000,'MI 9')

In [16]:
m1.p

10000

In [17]:
m1.m

'MI 9'

In [18]:
m2 = MobilePhone(60000,'Samsung S 10')

In [50]:
#variable = attribute
#function = method

class Bank:
    
    #class atrubute/object attribute
    Bank_name = 'SBI' # class attribute
    
    def __init__(self,branch,employees):
        
        self.branch = branch
        self.employees = employees
        
    def acc_opening(self):        
        print("Bank has digitalized account opening process")

In [51]:
b1 = Bank('Andheri',10)
b2 = Bank('Thane',12)

In [52]:
b1.Bank_name

'SBI'

In [53]:
b1.employees

10

In [54]:
#b1.acc_opening
b1.acc_opening()

Bank has digitalized account opening process


In [26]:
b2.Bank_name

'SBI'

In [55]:
#accessing a value from __init__ --> use self
class Bank:
    
    Bank_name = 'SBI' # class attribute
    
    def __init__(self,branch,employees,acc):
        
        self.branch = branch
        self.employees = employees
        self.accounts = acc
        
    def acc_opening(self):        
        print("Bank has digitalized account opening process and opened {} accounts".format(self.accounts))

In [56]:
b3 = Bank('Dadar',20,1200)

In [57]:
print(b3.accounts)
b3.acc_opening()

1200
Bank has digitalized account opening process and opened 1200 accounts


In [58]:
#passing a value in a method from outside --> no need to use self
class Bank:
    
    Bank_name = 'SBI' # class attribute
    
    def __init__(self,branch,employees):
        
        self.branch = branch
        self.employees = employees
        
    def acc_opening(self,accounts):        
        print("Bank has digitalized account opening process and opened {} accounts".format(accounts))

In [59]:
b5 = Bank('Churchgate',25)

In [60]:
b5.acc_opening(15000)

Bank has digitalized account opening process and opened 15000 accounts


In [63]:
class circle:
    
    pi = 3.14
    
    def __init__(self,radius=1):
        self.radius = radius
        
    def perimeter(self):
        print('Circumference of the Circle is :  ',2*self.pi*self.radius)

In [64]:
c1 = circle()
c1.perimeter()

Circumference of the Circle is :   6.28


In [65]:
c2 = circle(10)
c2.perimeter()

Circumference of the Circle is :   62.800000000000004


Write a program which has a class 'Calculate' and it does two mathematical operations

1. Calculates the distance between two input data points (x1,y1) and (x2,y2)
2. Calculates slope between two input data points (x1,y1) and (x2,y2)

In [68]:
class calculate():
    
    def __init__(self,x1y1,x2y2):
        self.x1y1 = x1y1
        self.x2y2 = x2y2
        
    def calc_distanc(self):
        x1,y1 = self.x1y1
        x2,y2 = self.x2y2
        
        return ((y2-y1)**2 + (x2-x1)**2)**0.5

    def calc_slope(self):
        x1,y1 = self.x1y1
        x2,y2 = self.x2y2
        
        return (y2-y1)/(x2-x1)

In [69]:
c1 = (-1,12)
c2 = (22,10)

obj1 = calculate(c1,c2)

In [70]:
obj1.calc_distanc()

23.08679276123039

In [71]:
obj1.calc_slope()

-0.08695652173913043

In [79]:
from calculate_script import calculate

In [80]:
c1 = (-1,22)
c2 = (12,20)

obj2 = calculate(c1,c2)

In [82]:
obj1.calc_distanc()

13.152946437965905

In [83]:
obj1.calc_slope()

-0.15384615384615385

In [84]:
import numpy as np # loaded with mathematical functions and opertions
import time

In [92]:
#let's declare the size
Size = 100000000

# Creating two lists
list1 = range(Size)
list2 = range(Size)

# Creating two NumPy arrays
arr1 = np.arange(Size)
arr2 = np.arange(Size)

# Calculating time for Python list
start = time.time()
result1 = [(x + y) for x, y in zip(list1, list2)]

print("Time for Python List in msec: ", (time.time() - start) )

# Calculating time for NumPy array
start = time.time()
result2 = (arr1 + arr2)

print("Time for NumPy array in msec: ", (time.time()- start) )

Time for Python List in msec:  8.080451965332031
Time for NumPy array in msec:  1.071012258529663


In [108]:
for x, y in zip((1,1), (2,2)):    
    print('X --> ',x,'  Y -->',y)

X -->  1   Y --> 2
X -->  1   Y --> 2


In [93]:
#defining a numpy array
intarray = np.array([1,2,3,4,5,6],int)

In [94]:
type(intarray)

numpy.ndarray

In [95]:
intarray

array([1, 2, 3, 4, 5, 6])

In [97]:
intarray[2]

3

In [98]:
#slicing
intarray[ : 2]

array([1, 2])

In [99]:
intarray1 = np.array([1,2,3,4,5,6],int)
intarray2 = np.array([17,16],int)

In [100]:
np.concatenate((intarray1,intarray2))

array([ 1,  2,  3,  4,  5,  6, 17, 16])

In [101]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [102]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [104]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [106]:
#Array of range of numbers
rangearray = np.array(np.arange(10))
rangearray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
floatarray = np.array([[1,2,3],[4,5,6]], float)
floatarray

array([[1., 2., 3.],
       [4., 5., 6.]])

In [110]:
#check the dimesnsion using shape
floatarray.shape

(2, 3)

In [112]:
rangearray.shape

(10,)

In [114]:
#change the dimension of an array using reshape
rangearray = rangearray.reshape(5,2)
rangearray

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [115]:
#restore into one dimesion
rangearray = rangearray.flatten()
rangearray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
arr1 = np.array([[1,2],[3,4]],int)
arr2 = np.array([[11,12],[13,14]],int)
print(arr1,'\n')
print(arr2,'\n')

[[1 2]
 [3 4]] 

[[11 12]
 [13 14]] 



In [117]:
arr1 + arr2

array([[12, 14],
       [16, 18]])

In [118]:
arr1*arr2

array([[11, 24],
       [39, 56]])

In [119]:
np.log(arr2)

array([[2.39789527, 2.48490665],
       [2.56494936, 2.63905733]])

In [120]:
np.sqrt(arr1)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [121]:
arr1.sum()

10

In [123]:
arr2.max()

14

In [124]:
arr2.mean()

12.5

In [125]:
arr2.std() #standard deviation

1.118033988749895

In [127]:
arr3 = np.array([1,2,1,4,5,6,6,7])

In [128]:
np.unique(arr3)

array([1, 2, 4, 5, 6, 7])

In [129]:
np.sort(arr3)

array([1, 1, 2, 4, 5, 6, 6, 7])

In [131]:
np.unique?

In [135]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
x, y = np.unique(a, return_index=True)

In [133]:
x

array(['a', 'b', 'c'], dtype='<U1')

In [136]:
y

array([0, 1, 3])